-- ============================================================
-- TOKOKASIR DATABASE
-- PostgreSQL / Supabase
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT NOT NULL,

  email TEXT NOT NULL UNIQUE,

  password_hash TEXT NOT NULL,

  role TEXT NOT NULL DEFAULT 'user'
    CHECK (role IN ('user', 'admin')),

  plan TEXT NOT NULL DEFAULT 'free'
    CHECK (plan IN ('free', 'pro', 'business')),

  subscription_status TEXT NOT NULL DEFAULT 'active'
    CHECK (
      subscription_status IN (
        'active',
        'expired',
        'cancelled'
      )
    ),

  subscription_expires_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id BIGINT NOT NULL
    REFERENCES public.users(id)
    ON DELETE CASCADE,

  plan TEXT NOT NULL
    CHECK (plan IN ('pro', 'business')),

  amount INTEGER NOT NULL
    CHECK (amount > 0),

  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (
      status IN (
        'pending',
        'approved',
        'rejected'
      )
    ),

  payment_method TEXT NOT NULL DEFAULT 'qris',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  verified_at TIMESTAMPTZ
);


CREATE INDEX IF NOT EXISTS idx_users_email
ON public.users(email);


CREATE INDEX IF NOT EXISTS idx_payments_user_id
ON public.payments(user_id);


CREATE INDEX IF NOT EXISTS idx_payments_status
ON public.payments(status);


CREATE INDEX IF NOT EXISTS idx_payments_user_plan_status
ON public.payments(
  user_id,
  plan,
  status
);


CREATE OR REPLACE FUNCTION
public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

  NEW.updated_at = NOW();

  RETURN NEW;

END;
$$;


DROP TRIGGER IF EXISTS
update_users_updated_at
ON public.users;


CREATE TRIGGER
update_users_updated_at

BEFORE UPDATE

ON public.users

FOR EACH ROW

EXECUTE FUNCTION
public.update_updated_at_column();


-- ============================================================
-- SECURITY
--
-- Tabel diakses melalui backend TokoKasir.
-- Browser/frontend tidak diberi akses langsung.
-- ============================================================

ALTER TABLE public.users
ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.payments
ENABLE ROW LEVEL SECURITY;

